version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRS_PASSWORD=default
      - POSTGRES_DB=willnichthaben
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

